version: "3.2"

services:
  tenancy-information-api:
    image: tenancy-information-api
    build:
      context: TenancyInformationApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=entitycorex;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  tenancy-information-api-test:
    image: tenancy-information-api-test
    build:
      context: .
      dockerfile: TenancyInformationApi.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    links:
      - test-database
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env
